# Generated by Django 5.1.4 on 2025-01-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='cipher_text',
            field=models.TextField(blank=True),
        ),
    ]
