# Generated by Django 5.1.4 on 2025-01-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_file_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='salt',
            field=models.TextField(blank=True),
        ),
    ]
